### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by dmerejkowsky** [TankerHQ/ruplacer#40]
So that we can have pre-compiled binaries for all 3 platforms

**Comment by dmerejkowsky** [comment]
Done in #39

**Comment by sergeevabc** [comment]
@dmerejkowsky, could you be so kind to update a binary for Windows?

**Comment by dmerejkowsky** [comment]
I *think* all we have to do is make a `0.5.0` release - GitHub Actions is set up and *should* automatically generate binaries for Linux, macOS and Windows.

But I'm no longer part of the TankerHQ GitHub organisation so I can't do it just yet.

**Comment by sergeevabc** [comment]
> @dmerejkowsky
> I think all we have to do is make a 0.5.0 release 
> But I'm no longer part of the TankerHQ

Dear @AlexandreBossard, @blastrock, @jeremad, @maximerety, and @theodelrieu, we need you assistance here, I guess.

**Comment by dmerejkowsky** [comment]
Done - expect a new release soonish :)

**Comment by sergeevabc** [comment]
Err… Sorry to bother you 10 days later, but is there any progress?
I am looking to update Windows binary [0.4.1][1] to something fresher, because of the controversial pattern highlighting as follows

Source: [in.txt](https://github.com/dmerejkowsky/ruplacer/files/6243265/in.txt)

``` console
$ ruplacer.exe "(?:<font.*ffffff.*>)([\s\S]*)(?:</font>)" $1 in.txt
```

![](https://i6.imageban.ru/out/2021/04/01/4f63f151d38e34211e3cac0d07d8b4f6.png)

[1]: https://github.com/dmerejkowsky/ruplacer/releases/tag/v0.4.1

**Comment by sergeevabc** [comment]
Aggrrhh. Beloved Ruplacer 0.10 does not work Windows 7 x64, 0.8.3 seems to be the last version that works fine here. Could you be so kind to add another build that supports my OS? https://doc.rust-lang.org/nightly/rustc/platform-support/win7-windows-msvc.html
